run:
  folder: checkpoint
  name: vqgan.vae-128

logging:
  filename: log.log
  interval: 100
  frequent_until: 100
  frequent_interval: 5

repr:
  seed: 3407
  use_deterministic_algorithms: true
  warn_only: true
  cudnn_benchmark: false

data:
  image_size: 128
  dataset_dir: data/imagenet/train

  batch_size: 16
  num_workers: 8

model:
  num_embeddings: 4096
  embed_dim: 8
  block_out_channels: [64, 128, 256]
  layers_per_block: 1
  activation: swish
  image_channels: 3
  residual_scale_init: 0.001
  latent_dim: null

discriminator:
  in_channels: ${model.image_channels}
  block_out_channels: [32, 64, 128, 256, 256]  # output: 8x8
  layers_per_block: 1
  norm_groups: 32
  activation: lrelu
  residual_scale_init: ${model.residual_scale_init}

optimizer:
  lr: 0.0001
  betas:
  - 0.0
  - 0.99

env:
  compile: null
  strategy: ddp  # change to ddp for dist.

train:
  num_iterations: 200000

  gan_lambda: 0.1
  gp_every: -1
  gp_lambda: 10.0

  running: 100
  save_every: 10000
